version: '3.1'

services:

  puma-delivery:
    container_name: pumas 
    image: mariadb:latest
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: rootroot
      MARIADB_ROOT_HOST: '%'
      MARIADB_DATABASE: 'puma'
    ports:
      - "3306:3306"